#ifndef BROKER_INTERCEPTOR_EBPF_CONTROL_AUTHZ_CODES_H
#define BROKER_INTERCEPTOR_EBPF_CONTROL_AUTHZ_CODES_H

typedef enum broker_control_authz_error_code {
  BROKER_CTRL_AUTH_UNSPECIFIED = 0,
  BROKER_CTRL_AUTH_PEERCRED_UNAVAILABLE = 1,
  BROKER_CTRL_AUTH_PEERCRED_REJECTED_UID = 2,
  BROKER_CTRL_AUTH_PEERCRED_REJECTED_GID = 3,
  BROKER_CTRL_AUTH_SOCKET_MODE_INVALID = 4,
  BROKER_CTRL_AUTH_SOCKET_OWNER_INVALID = 5
} broker_control_authz_error_code_t;

#endif
