#ifndef BROKER_INTERCEPTOR_EBPF_REASON_CODES_H
#define BROKER_INTERCEPTOR_EBPF_REASON_CODES_H

typedef enum broker_dataplane_verdict_reason_code {
  BROKER_DP_REASON_UNSPECIFIED = 0,
  BROKER_DP_REASON_UNMANAGED_ALLOW = 1,
  BROKER_DP_REASON_OBSERVE_WOULD_ALLOW = 2,
  BROKER_DP_REASON_OBSERVE_WOULD_DENY_EXPLICIT = 3,
  BROKER_DP_REASON_OBSERVE_WOULD_DENY_DEFAULT = 4,
  BROKER_DP_REASON_ALLOW_EXPLICIT = 5,
  BROKER_DP_REASON_ALLOW_BROKER = 6,
  BROKER_DP_REASON_ALLOW_DNS = 7,
  BROKER_DP_REASON_DENY_EXPLICIT = 8,
  BROKER_DP_REASON_DENY_DEFAULT = 9,
  BROKER_DP_REASON_DENY_DEGRADED_FAIL_CLOSED = 10,
  BROKER_DP_REASON_ALLOW_DEGRADED_FAIL_OPEN = 11
} broker_dataplane_verdict_reason_code_t;

#endif
